name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        cp --force LICENSE.txt module/.
        cp --force README.md module/.
        MODULE_VERSION=$(grep -oP '(?<="version": ")[^"]+' module/module.json | tr -d '\n')
        perl -pi -E "s|latest/download/six-feet-under\\.zip|download/release-$MODULE_VERSION/six-feet-under.zip|" module/module.json
        echo "moduleVersion=$MODULE_VERSION" >> $GITHUB_ENV

    - run: cd module && zip -r ../six-feet-under.zip ./*

    - name: Create Version Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: false
        artifacts: './module/module.json, ./six-feet-under.zip'
        draft: false
        name: release-${{ env.moduleVersion }}
        prerelease: true
        tag: release-${{ env.moduleVersion }}
        token: ${{ secrets.GITHUB_TOKEN }}
